import { Suspense } from "react";
import "./globals.css";
import LoadingComponent from "@/components/LoadingComponent";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
      <Suspense fallback={<LoadingComponent/>}>
      {children}
      </Suspense>
      </body>
    </html>
  );
}
